GET http://localhost:8080/api
Accept: application/json

###

GET http://localhost:8080/api/sections
Accept: application/ld+json

###

POST http://localhost:8080/api/sections
Authorization: Bearer !ChangeMe!
Accept: application/ld+json
Content-Type: application/ld+json

{
  "name": "test2",
  "title": "second",
  "orderIndex": 1
}

###

PUT http://localhost:8080/api/metrics/main_coverage
Authorization: Bearer !ChangeMe!
Accept: application/ld+json
Content-Type: application/ld+json

{
  "name": "main_coverage",
  "section": "/api/sections/main",
  "title": "Coverage",
  "format": {
    "decimalsCount": 2,
    "decimalPoint": ".",
    "thousandsSeparator": "",
    "unit": "%"
  },
  "orderIndex": 5
}

###


POST http://localhost:8080/api/batch-values
Authorization: Bearer !ChangeMe!
Accept: application/ld+json
Content-Type: application/ld+json

[
  {
    "metric": "/api/metrics/main_coverage",
    "createdAt": "2019-10-22T17:41:31.059Z",
    "value": 110.123,
    "tag": "master"
  }
]

###
